// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kknlnyyurqymeegnsbhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbmxueXl1cnF5bWVlZ25zYmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTQyMTcsImV4cCI6MjA3NDE5MDIxN30.WQOwXO60WK2GOeCOtBitjd2Kdds6kV4Z6XKmOwGGqE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});